config/routes.rb
Rails.application.routes.draw do

  resources :items
  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

private

  def item_params
    params.require(:item).permit(:name, :description, :start_date, :start_time, :end_time)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/index.html.erb
<div><% @items.each do |item|%>
  <div><%= item.name %></br>
  <%= item.description %></br>
  <%= item.start_time %></br>
  <%= item.end_time %></br></div>
<% end %></div>

<%= link_to "Add a new item", new_item_path %>

app/views/items/new.html.erb
<%= form_for @item do |f| %>
  <%= f.label "Item name:" %>
  <%= f.text_field :name %></br>
  <%= f.label "Item description:" %>
  <%= f.text_area :description %></br>
  <%= f.label "Date for item:" %>
  <%= f.date_field :start_date %></br>
  <%= f.label "Start time for item:" %>
  <%= f.time_field :start_time %></br>
  <%= f.label "End time for item:" %>
  <%= f.time_field :end_time %></br>
  <%= f.submit "Create item" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>